version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Spécifie le fichier Dockerfile
    image: elohim237/repoevaluation:latest
    container_name: evaluation
    environment:
      DATABASE_URL: mysql://user:GradeForecast1@mysqlGrade:3306/bd_noteforecast
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    networks:
      - backend

  mysql:
    container_name: mysqlGrade
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Grade
      MYSQL_DATABASE: bd_noteforecast
      MYSQL_USER: user
      MYSQL_PASSWORD: GradeForecast1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  proxy:
    container_name: proxy
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
