version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  mysql:
    container_name: mysql
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:password@localhos/bd_noteforecast
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
        - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
