# Utiliser une image de base officielle Node.js
FROM node:16.18-buster-slim

COPY . ./app

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances
RUN npm install 
RUN npm install -g @swc/cli @swc/core
# Ajouter openssl à l'installation
RUN apt-get update -y && apt-get install -y openssl

# Générez le client Prisma
RUN npx prisma generate

# Appliquez les migrations Prisma (lors de la construction de l'image)
# Utilisez `npx prisma migrate deploy` pour appliquer les migrations dans un environnement de production


ENV NODE_ENV production

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3001

# Démarrer l'application
CMD ["npm", "run", "start"]
